services:
  db:
    image: postgres:14-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: tasks_manager_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: U7qP!9xZJ4fC_w8M
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
